
####################
## Auto Formatter ##
####################

name: Format Code

# Documentation:
# https://github.com/mezgoodle/auto-formatter

#############################
# Start the job on all push #
#############################
on:
  #push:
  #  branches: [master]
  pull_request:
    branches-ignore: [master]
    # Remove the line above to run when pull-requesting to master

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Format code
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Check out code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0

      ################################
      # Run Auto-formatter against code base #
      ################################
      - name: Run auto-formatter
        uses: mezgoodle/auto-formatter@v1.0.10
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
