--
name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: sudo apt install tidy
      - run: tidy --indent auto --indent-spaces 2 --tidy-mark no --force-output yes -o new_index.html index.html
      - name: Print generated page
        run: cat new_index.html
