# test

name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: sudo apt install tidy
      - run: tidy --config tidy.conf index.html
      - name: Print generated page
        run: cat index.html
